# Generated by Django 5.1.3 on 2024-11-13 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pavilion', '0003_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='company',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
